[pytest]
python_files = test_*.py
testpaths = tests
addopts = --headed --browser chromium -q

markers =
    smoke: smoke tests
    regression: regression tests
    e2e: end-to-end tests

allure_features = SauceDemo Automation Framework